---
language: python
python: 2.7
sudo: false
cache:
  directories:
    - eggs
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script: make show test
env:
  - BUILDOUT_FILENAME=buildout-plone-4.x.cfg
  - BUILDOUT_FILENAME=buildout-plone-5.x.cfg
